version: 0.1
env:
  variables:
    S3_BUCKET: "movies-api-deployment-packages"
    PACKAGE: "github.com/clarencesiah/aws-go-lambda"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname "github.com/clarencesiah/aws-go-lambda")"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/github.com/clarencesiah/aws-go-lambda"

  pre_build:
    commands:
        # Check what $GOPATH and $GOBIN are currently
      - echo "GOPATH = ${GOPATH}\nGOBIN = ${GOBIN}"

        # Set them relative to your home directory
      - pwd
      - ls -R
      - mkdir bin
      - set GOPATH=$HOME && set GOBIN=$GOPATH/bin
      - echo "GOPATH = ${GOPATH}\nGOBIN = ${GOBIN}"
      - cd "/go/src/github.com/clarencesiah/aws-go-lambda"
      - pwd
      - ls -R

  build:
    commands:
      - GOOS=linux go build -o main
      - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip main
      - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_BUCKET/

  post_build:
    commands:
      - aws lambda update-function-code --function-name FindAllMovies --s3-bucket $S3_BUCKET --s3-key $CODEBUILD_RESOLVED_SOURCE_VERSION.zip