version: 0.1
env:
  variables:
    S3_BUCKET: "movies-api-deployment-packages"
    PACKAGE: "github.com/clarencesiah/aws-go-lambda"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

  pre_build:
    commands:
        # Check what $GOPATH and $GOBIN are currently
      - echo "GOPATH = ${GOPATH}\nGOBIN = ${GOBIN}"

        # Set them relative to your home directory
      - export GOPATH=$HOME && export GOBIN=$GOPATH/bin
      - echo "GOPATH = ${GOPATH}\nGOBIN = ${GOBIN}"
      - cd "/go/src/${PACKAGE}"
      - ls
      - export GOPATH=$HOME
      - go get -v ./...

  build:
    commands:
      - GOOS=linux go build -o main
      - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip main
      - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_BUCKET/

  post_build:
    commands:
      - aws lambda update-function-code --function-name FindAllMovies --s3-bucket $S3_BUCKET --s3-key $CODEBUILD_RESOLVED_SOURCE_VERSION.zip