version: 0.1
env:
  variables:
    S3_BUCKET: "movie-api-deployment-packages"
    PACKAGE: "github.com/clarencesiah/aws-go-lambda"

phases:
  #install:
    #commands:
        #- pwd

  pre_build:
    commands:
        # Set them relative to your home directory
        # Set ${GOPATH} to different path also not working, don't know why?
        #- echo ${GOPATH}
        #- pwd
        #- ls -R
        #- GOPATH=${GOPATH}/src
        #- echo ${GOPATH}
        - mkdir src
        - cp -a ./main.go ./src/
        - go get -v ./src/...

  build:
    commands:
        - GOOS=linux go build -o main
        - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip main
        - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
        - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://movie-api-deployment-packages/

  post_build:
    commands:
        - aws lambda update-function-code --function-name FillAllMovie --s3-bucket movie-api-deployment-packages --s3-key $CODEBUILD_RESOLVED_SOURCE_VERSION.zip