ersion: 0.1
env:
  variables:
    S3_BUCKET: "movies-api-deployment-packages"
    PACKAGE: "github.com/clarencesiah/aws-go-lambda"

phases:

  pre_build:
    commands:
        # Set them relative to your home directory
        # Set ${GOPATH} to different path also not working, don't know why?
        #- echo ${GOPATH}
        #- pwd
        #- ls -R
        #- GOPATH=${GOPATH}/src
        #- echo ${GOPATH}
      - cp -a ./main.go ./src/
      - go get -v ./src/...

  build:
    commands:
      - GOOS=linux go build -o main
      - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip main
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_BUCKET/
      